module.exports = {
	mongo_host: "163.172.6.28",
	mongo_port: 27017,
	mongo_db: "dashup",  
	mongo_user: "root",
	mongo_password: "713a2b05",
	cache_time: 1000 * 60 * 60,
	smtp_user: 'ramazan.donmez@live.com',
	smtp_pass: "nBcMdNNN1LF6bSB1Ly2kGA",
	smtp_from: "domain.manager.20@gmail.com",
	smtp_to: "domain.manager.20@gmail.com",
	mail_subject: "New Feedback Message",
	recaptca_verify_endpoint: "https://www.google.com/recaptcha/api/siteverify",
	recaptcha_site_key: "6LcPhBwTAAAAAK4O0N-wflLF0ymy2D2w_SnLm_E8",
	recaptcha_secret_key: "6LcPhBwTAAAAAA8z84QCSH3A863Hc3zkT9Lpjcxl",
	session_secret: "digilab_123öasdjf",
	app_name: "dashup",
	app_domain: "dash-up.com",
	brand_name: "Dashbup",
	title_bracket: "- ",
	ga_client_id: "776918795642-o99gopmf5lgn494hlb8nr97mtk7rrn1j.apps.googleusercontent.com",
	ga_client_secret: "Dq9V91yb_JuPOtMYIe3HI47C",
	ga_redirect_uri: "http://localhost:3000/auth/ga-oauth2-callback"
}